paths:
  /amm/trade:
    post:
      summary: 'Perform a trade on an AMM'
      operationId: 'trade'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/TradeRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/TradeResponse'

  /amm/price:
    post:
      summary: 'Get the price for a quote base pair on an AMM'
      operationId: 'poll'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/PriceRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/PriceResponse'
  
  /amm/liquidity/add:
    post:
      summary: 'Add liquidity to a pool'
      operationId: 'add'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/AddLiquidityRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/AddLiquidityResponse'

  /amm/liquidity/add:
    post:
      summary: 'Remove liquidity from a pool'
      operationId: 'remove'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/RemoveLiquidityRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/RemoveLiquidityResponse'
